[package]
name = "hypervisor"
version = "2.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
license = "Mulan PSL v2"

[dependencies]
arc-swap = "1.6.0"
thiserror = "1.0"
anyhow = "1.0"
kvm-bindings = { version = "0.6.0", features = ["fam-wrappers"] }
kvm-ioctls = "0.13.0"
log = "0.4"
vmm-sys-util = "0.11.1"
once_cell = "1.18.0"
util = { path = "../util" }
